Assuming unrestricted shared filesystem usage.
None
host: Allens MacBook
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                  count
-----------------  -------
write_dset_config        1
total                    1

Select jobs to execute...
Execute 1 jobs...
[Fri Aug 22 16:14:29 2025]
localrule write_dset_config:
    output: isoformDB/configs/K562.json
    jobid: 0
    reason: Missing output files: isoformDB/configs/K562.json
    wildcards: dataset_id=K562
    resources: tmpdir=/var/folders/tk/bdsgytmn5cb0bfqrftv10n8r0000gq/T
Shell command: None
Traceback (most recent call last):

  File "/Users/allen/miniconda3/envs/isoformer/lib/python3.12/site-packages/snakemake/executors/local.py", line 232, in spawn_job
    subprocess.check_call(cmd, shell=True)

  File "/Users/allen/miniconda3/envs/isoformer/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'cd /Users/allen/projects/dna_lang/pytorch_borzoi/isoformer/database/pipeline && /Users/allen/miniconda3/envs/isoformer/bin/python3.12 -m snakemake --snakefile '/Users/allen/projects/dna_lang/pytorch_borzoi/isoformer/database/pipeline/isoform_db.smk' --target-jobs 'write_dset_config:dataset_id=K562' --allowed-rules write_dset_config --cores 1 --attempt 1 --force-use-threads  --force --target-files-omit-workdir-adjustment --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --rerun-triggers params code mtime input software-env --deployment-method conda --conda-frontend 'conda' --conda-base-path '/Users/allen/miniconda3' --shared-fs-usage input-output persistence software-deployment sources storage-local-copies source-cache --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --printshellcmds  --latency-wait 5 --scheduler 'greedy' --local-storage-prefix base64//LnNuYWtlbWFrZS9zdG9yYWdl --scheduler-solver-path '/Users/allen/miniconda3/envs/isoformer/bin' --configfiles /Users/allen/projects/dna_lang/pytorch_borzoi/isoformer/database/pipeline/config.yaml --default-resources base64//dG1wZGlyPXN5c3RlbV90bXBkaXI= --quiet progress rules host --mode 'subprocess' --local-groupid 'local'' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Users/allen/miniconda3/envs/isoformer/lib/python3.12/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/allen/miniconda3/envs/isoformer/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)

  File "/Users/allen/miniconda3/envs/isoformer/lib/python3.12/site-packages/snakemake/executors/local.py", line 234, in spawn_job
    raise SpawnedJobError()

snakemake.exceptions.SpawnedJobError

[Fri Aug 22 16:14:31 2025]
Error in rule write_dset_config:
    message: None
    jobid: 0
    output: isoformDB/configs/K562.json
Shutting down, this might take some time.
Exiting because a job execution failed. Look below for error messages
[Fri Aug 22 16:14:31 2025]
Error in rule write_dset_config:
    message: None
    jobid: 0
    output: isoformDB/configs/K562.json
Complete log(s): /Users/allen/projects/dna_lang/pytorch_borzoi/isoformer/database/pipeline/.snakemake/log/2025-08-22T161429.906282.snakemake.log
WorkflowError:
At least one job did not complete successfully.
